import fs from 'fs';
import path from 'path';

const routinesPath = path.resolve('./src/data/routines.ts');
let content = fs.readFileSync(routinesPath, 'utf-8');

const updates = {
  'w-shadow-boxing': 'Objetivo: Elevación rápida de frecuencia cardíaca y flujo sanguíneo al tren superior.\n\nEjecución:\n- Adopta una guardia de boxeo básica.\n- Lanza combinaciones de golpes al aire de forma rítmica.\n\nPunto Clave: El poder del golpe viene de la rotación de la cadera y oblicuos. No lances los codos hasta su máxima extensión.',
  'w-dislocaciones': 'Objetivo: Movilizar la cápsula articular del hombro y estirar el pectoral.\n\nEjecución:\n- Agarra un palo o toalla con agarre ancho.\n- Con brazos rectos, eleva por encima de la cabeza hacia la espalda baja.\n- Regresa a la posición inicial.\n\nPunto Clave: Movimiento fluido sin dolor. No flexiones los codos.',
  'w-oruga': 'Objetivo: Activar el core, estabilizadores del hombro y estirar la cadena posterior.\n\nEjecución:\n- De pie, dóblate desde la cadera y toca el suelo.\n- Camina con las manos hasta plancha alta.\n- Contrae glúteos y abdomen por 2-3s.\n- Camina hacia atrás y ponte de pie.\n\nPunto Clave: No dejes que la cadera se hunda en la plancha.',
  'w-press-z': 'Objetivo: Fuerza de empuje vertical y estabilización extrema del core.\n\nEjecución:\n- Siéntate en el suelo con piernas estiradas (en "L").\n- Empuja mancuernas hacia arriba hasta bloquear codos.\n- Baja con control.\n\nPunto Clave: Al estar sentado sin respaldo, no puedes usar trampa. Si el peso te tira atrás, baja el peso.',
  'w-remo-ren': 'Objetivo: Tracción horizontal pesada bajo fatiga y resistencia anti-rotacional.\n\nEjecución:\n- Plancha alta apoyado sobre mancuernas, pies anchos.\n- Jala una mancuerna hacia tu cadera.\n- Baja lentamente y repite con el otro brazo.\n\nPunto Clave: LA CADERA NO GIRE al levantar el brazo.',
  'circuito-hiit': '1. Shadow Boxing c/mancuernas (1-2 kg)\n2. Press Z pesado\n3. Remo Renegado a fallo\n4. Floor Press explosivo\n\nFloor Press Explosivo:\nObjetivo: Empuje horizontal con énfasis en potencia metabólica.\nEjecución:\n- Acuéstate boca arriba, rodillas dobladas.\n- Codos a 45 grados.\n- Empuja explosivamente hacia el techo.\n- Baja controlado hasta que tríceps toquen el suelo. Micro-pausa y repite.\nPunto Clave: La pausa en el suelo evita el rebote y protege los hombros.',
  'w-estiramiento-mundo': 'Objetivo: Movilizar cadera, columna torácica y estirar isquiosurales/glúteos.\n\nEjecución:\n- Paso largo adelante con pierna derecha.\n- Manos al suelo por el interior del pie.\n- Pierna trasera estirada, despega mano derecha y gira torso apuntando al techo.\n- Sostén 1s, baja y cambia de pierna.\n\nPunto Clave: No dejes que la rodilla de atrás toque el suelo.',
  'w-oruga-plancha': 'Objetivo: Activar el core, estabilizadores del hombro y estirar la cadena posterior.\n\nEjecución:\n- De pie, dóblate desde la cadera y toca el suelo.\n- Camina con las manos hasta plancha alta.\n- Contrae glúteos y abdomen por 2-3s.\n- Camina hacia atrás y ponte de pie.\n\nPunto Clave: No dejes que la cadera se hunda en la plancha.',
  'w-sentadilla-dinamica': 'Objetivo: Lubricar cadera, rodillas y tobillos; preparar SNC.\n\nEjecución:\n- Pies anchura de hombros, puntas hacia afuera.\n- Desciende profundo sin peso, torso erguido.\n- Usa codos para empujar rodillas afuera.\n- Pausa profunda ("en el hoyo") por 2s exactos.\n- Sube explosivamente.\n\nPunto Clave: Pecho hacia adelante. Si los talones se levantan, baja menos.',
  'sentadilla-barra': 'Objetivo: Tensión mecánica global del tren inferior.\n\nEjecución:\n- Barra sobre trapecios.\n- Pies algo más anchos que la cadera.\n- Desciende enviando cadera atrás y doblando rodillas. Pecho alto.\n- Rompe el paralelo si la movilidad lo permite.\n- Empuja el suelo para subir.\n\nPunto Clave: Tensión en abdomen. Rodillas siguen la línea de los pies, nunca colapsan hacia adentro.',
  'pmr-barra': 'Objetivo: Desarrollo de isquiosurales, glúteos y erectores espinales.\n\nEjecución:\n- Flexiona LIGERAMENTE las rodillas y fija el ángulo.\n- Empuja cadera hacia atrás ("cerrar puerta con el trasero").\n- Barra roza los muslos. Espalda recta.\n- Baja hasta sentir estiramiento profundo.\n- Empuja cadera adelante para subir.\n\nPunto Clave: Es una bisagra de cadera, no sentadilla. Si la barra se separa de las piernas, cargas la zona lumbar.',
  'zancadas-inv': 'Objetivo: Trabajo unilateral de cuádriceps y glúteo.\n\nEjecución:\n- Sostén mancuernas.\n- Paso largo hacia ATRÁS.\n- Desciende rodilla trasera hacia el suelo (sin golpear).\n- Empuja con pie delantero para volver.\n\nPunto Clave: Paso atrás reduce fuerza de cizalla en rodilla. Torso ligeramente inclinado para mayor trabajo de glúteo.',
  'elev-talones': 'Objetivo: Hipertrofia del Gastrocnemio.\n\nEjecución:\n- Puntas de pies sobre escalón.\n- Deja caer talones al máximo (pausa 1-2s).\n- Sube sobre puntas contrayendo (pausa 1s).\n\nPunto Clave: El rebote anula el trabajo. La pausa larga abajo es obligatoria.',
  'w-dislocaciones-2': 'Objetivo: Movilizar la cápsula articular del hombro y estirar el pectoral.\n\nEjecución:\n- Agarra un palo o toalla con agarre ancho.\n- Con brazos rectos, eleva por encima de la cabeza hacia la espalda baja.\n- Regresa a la posición inicial.\n\nPunto Clave: Movimiento fluido sin dolor. No flexiones los codos.',
  'floor-press': 'Objetivo: Empuje horizontal con énfasis en potencia metabólica.\n\nEjecución:\n- Acuéstate boca arriba, rodillas dobladas.\n- Codos a 45 grados.\n- Empuja explosivamente hacia el techo.\n- Baja controlado hasta que tríceps toquen el suelo. Micro-pausa y repite.\n\nPunto Clave: La pausa en el suelo evita el rebote y protege los hombros.',
  'remo-barra': 'Objetivo: Grosor del dorso ancho y romboides.\n\nEjecución:\n- Agarre más ancho que hombros.\n- Bisagra de cadera hasta torso casi paralelo al suelo.\n- Jala la barra hacia ombligo/cadera baja.\n- Deprime omóplatos antes de doblar codos.\n- Baja con control.\n\nPunto Clave: Si el torso se levanta, usas inercia. Mantén torso rígido y paralelo al piso.',
  'press-militar': 'Objetivo: Fuerza y tamaño de deltoides anteriores y medios.\n\nEjecución:\n- De pie, peso a altura de clavículas.\n- Aprieta glúteos y core.\n- Empuja en línea recta al techo hasta bloquear codos.\n- Baja con control.\n\nPunto Clave: Cero impulso de piernas. Si flexionas rodillas es Push Press.',
  'curl-biceps': 'Objetivo: Hipertrofia del bíceps braquial.\n\nEjecución:\n- Agarre supinación (palmas arriba).\n- Codos pegados a costillas.\n- Flexiona brazos llevando peso a hombros.\n- Baja controlando la excéntrica.\n\nPunto Clave: No uses balanceo con espalda baja.',
  'w-estiramiento-mundo-2': 'Objetivo: Movilizar cadera, columna torácica y estirar isquiosurales/glúteos.\n\nEjecución:\n- Paso largo adelante con pierna derecha.\n- Manos al suelo por el interior del pie.\n- Pierna trasera estirada, despega mano derecha y gira torso apuntando al techo.\n- Sostén 1s, baja y cambia de pierna.\n\nPunto Clave: No dejes que la rodilla de atrás toque el suelo.',
  'sentadilla-bulgara': 'Objetivo: Estrés metabólico y ROM extremo en glúteo/cuádriceps.\n\nEjecución:\n- Empeine trasero sobre banco.\n- Desciende rodilla trasera hacia el suelo.\n- Baja lo máximo posible para estirar glúteo.\n- Sube empujando con pie delantero.\n\nPunto Clave: ¡No bloquees la rodilla arriba! Detén el movimiento antes de estirar por completo para mantener oclusión vascular.',
  'pmr-mancuernas': 'Objetivo: Estiramiento fascial de isquiosurales.\n\nEjecución:\n- Rodillas AÚN MÁS RECTAS (sin bloquear).\n- Mancuernas cuelgan por los lados o frente a piernas.\n- Baja lentamente (3s) hasta estiramiento máximo.\n\nPunto Clave: El enfoque no es peso, es sentir el músculo desgarrándose en la bajada.',
  'sentadilla-goblet': 'Objetivo: Aislamiento del cuádriceps frontal.\n\nEjecución:\n- Sostén mancuerna vertical pegada al pecho ("copa").\n- Torso completamente vertical.\n- Baja profundo empujando rodillas adelante y abriéndolas.\n- Sube sin bloquear rodillas.\n\nPunto Clave: La carga frontal evita doblarse adelante, castigando 100% los cuádriceps.',
  'elev-talones-sentado': 'Objetivo: Hipertrofia del Sóleo.\n\nEjecución:\n- Sentado, rodillas a 90 grados.\n- Mancuernas pesadas sobre muslos.\n- Levanta talones al máximo, pausa, baja controlado.\n\nPunto Clave: Rodilla a 90 grados apaga el gastrocnemio, dejando el trabajo al sóleo.',
  'w-dislocaciones-3': 'Objetivo: Movilizar la cápsula articular del hombro y estirar el pectoral.\n\nEjecución:\n- Agarra un palo o toalla con agarre ancho.\n- Con brazos rectos, eleva por encima de la cabeza hacia la espalda baja.\n- Regresa a la posición inicial.\n\nPunto Clave: Movimiento fluido sin dolor. No flexiones los codos.',
  'press-suelo-espinal': 'Objetivo: Hipertrofia de pectoral con estiramiento bajo carga.\n\nEjecución:\n- Colchoneta enrollada en el suelo.\n- Acuéstate con la elevación en tu columna (entre omóplatos).\n- Realiza press con mancuernas.\n\nPunto Clave: El cojín levanta la caja torácica, permitiendo que codos bajen más allá de la espalda. Estiramiento extra.',
  'remo-uni': 'Objetivo: Desarrollo de dorsales sin carga axial.\n\nEjecución:\n- Rodilla y mano apoyadas en banco.\n- Torso paralelo al suelo.\n- Deja que mancuerna tire del hombro (estiramiento).\n- Jala hacia la cadera (no al pecho).\n\nPunto Clave: Movimiento como péndulo hacia la cadera, no serrucho arriba-abajo.',
  'elev-laterales': 'Objetivo: Anchura visual (deltoides lateral).\n\nEjecución:\n- Eleva brazos a los lados hasta paralelo al suelo.\n- Ligera flexión de codo.\n- Al final, imagina "verter agua" (rotación interna leve).\n\nPunto Clave: Cero balanceo. Mejor poco peso y altas reps buscando quemazón.',
  'super-brazos': 'Objetivo: Tríceps (cabeza larga) y Braquial.\n\nEjecución Rompecráneos:\n- Boca arriba, brazos al techo.\n- Flexiona codos bajando mancuernas a las sienes.\n- Extiende contrayendo tríceps (codos apuntan al techo).\n\nEjecución Curl Martillo:\n- De pie, agarre neutro.\n- Flexiona llevando mancuernas a hombros.\n\nPunto Clave: Sin descanso entre ejercicios.'
};

for (const [id, info] of Object.entries(updates)) {
  const regex = new RegExp(`(id:\\s*'${id}'[\\s\\S]*?info:\\s*')[^']*(')`, 'g');
  content = content.replace(regex, `$1${info.replace(/\n/g, '\\n')}$2`);
}

fs.writeFileSync(routinesPath, content, 'utf-8');
console.log('Updated routines.ts');
